---
name: context

path: .

windows:
  - name: code
    flex_direction: row
    panes:
      - name: Editor
        flex: 2
        commands:
          - command: ^$env.EDITOR
      - name: Opencode
        flex: 1
        commands:
          - command: ^opencode
            args:
              - --port

  - name: misc
    flex_direction: row
    panes:
      - flex: 1
        flex_direction: column
        panes:
          - flex: 1
            commands:
              - command: trunk
                args:
                  - serve
          - flex: 8
      - flex: 1
        flex_direction: column
        panes:
          - flex: 1
            commands:
              - command: cargo
                args:
                  - run
                  - --bin
                  - c5t
                  - api
          - flex: 8
